INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (1, 'PDL', 'Ponta Delgada Joao Paulo II', 'Portugal', 'Ponta Delgada');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (2, 'FAO', 'Faro Airport', 'Portugal', 'Faro');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (3, 'LIS', 'Portela', 'Portugal', 'Lisbon');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (4, 'OPO', 'Franciso De Sa Carneiro', 'Portugal', 'Porto');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (5, 'SJZ', 'Sao Jorge Airport', 'Portugal', 'Madeira');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (6, 'MAD', 'Madrid-Barajas Adolfo Suárez Airport', 'Spain', 'Madrid');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (7, 'AGP', 'Málaga-Costa del Sol Airport', 'Spain', 'Malaga');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (8, 'BCN', 'Josep Tarradellas Barcelona-El Prat Airport', 'Spain', 'Barcelona');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (9, 'PMI', 'Palma de Mallorca Airport', 'Spain', 'Mallorca');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (10, 'LPA', 'Gran Canaria Airport', 'Spain', 'Gran Canaria');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (11, 'BOD', 'Bordeaux Airport', 'France', 'Bordeaux');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (12, 'MRS', 'Marseille Provence Airport', 'France', 'Marseille');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (13, 'LYS', 'Lyon Saint Exupéry Airport', 'France', 'Lyon');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (14, 'CDG', 'Paris Charles de Gaulle Airport', 'France', 'Paris');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (15, 'PMO', 'Falcone Borsellino Airport', 'Italy', 'Palermo');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (16, 'CTA', 'Aeroporto di Catania Fontanarossa', 'Italy', 'Catania');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (17, 'BRI', 'Aeroporto Internazionale di Bari: Karol Wojtyla', 'Italy', 'Bari');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (18, 'CIA', 'Aeroporto Internazionale di Roma Ciampino G. B. Pastine', 'Italy', 'Rome');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (19, 'PSA', 'Aeroporto Internazionale Galileo Galilei Pisa', 'Italy', 'Pisa');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (20, 'TRN', 'Torino Airport', 'Italy', 'Torino');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (21, 'MIL', 'Aeroporto di Milano Linate', 'Italy', 'Milan');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (22, 'CAG', 'Cagliari Elmas Airport', 'Italy', 'Calgiari');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (23, 'MLA', 'Malta International Airport', 'Malta', 'Luqa');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (24, 'ZRH', 'Flughafen Zürich', 'Switzerland', 'Zurich');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (25, 'OTZ', 'Flughafen Wien', 'Austria', 'Wien');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (26, 'LJU', 'Letališče Jožeta Pučnika Ljubljana', 'Slovenia', 'Ljubljana');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (27, 'RJK', 'Zračna luka Rijeka', 'Croatia', 'Riejka');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (28, 'CFU', 'Αεροδρόμιο της Κέρκυρας', 'Greece', 'Corfu');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (29, 'ATH', 'Διεθνής Αερολιμένας Αθηνών', 'Greece', 'Athens');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (30, 'SKG', 'Κρατικός Αερολιμένας Νέας Αγχιάλου', 'Greece', 'Thessaloniki');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (31, 'JMK', 'Αεροδρόμιο Μυκόνου', 'Greece', 'Mykonos');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (32, 'CHQ', 'Αεροδρόμιο Χανίων Ιωάννης Δασκαλογιάννης', 'Greece', 'Chania');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (33, 'AYT', 'Antalya Havalimanı', 'Turkey', 'Antalya');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (34, 'SAW', 'Sabiha Gökçen Uluslararası Havalimanı', 'Turkey', 'Istambul');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (35, 'SKP', 'Меѓународен аеродром Скопје', 'North Macedonia', 'Skopje');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (36, 'WRO', 'Wrocław Nicolaus Copernicus Airport', 'Poland', 'Wroclaw');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (37, 'KRK', 'Kraków Airport im. Jana Pawła II', 'Poland', 'Krakow');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (38, 'WAW', 'Lotnisko Chopina', 'Poland', 'Warsaw');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (39, 'GDN', 'Port Lotniczy Gdańsk im. Lecha Wałęsy', 'Poland', 'Gdansk');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (40, 'MUC', 'Flughafen München', 'Germany', 'Munich');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (41, 'DUS', 'Flughafen Düsseldorf', 'Germany', 'Dusseldorf');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (42, 'TXL', 'Flughafen Berlin Tegel', 'Germany', 'Berlin');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (43, 'FRA', 'Frankfurt Flughafen', 'Germany', 'Frankfurt');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (44, 'NUE', 'Airport Nürnberg', 'Germany', 'Nurnberg');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (45, 'AMS', 'Amsterdam Airport Schiphol', 'Netherlands', 'Amsterdam');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (46, 'KOB', 'Københavns Lufthavn', 'Denmark', 'Copenhagen');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (47, 'AAL', 'Aalborg Lufthavn', 'Denmark', 'Aalborg');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (48, 'MMX', 'Malmö Airport', 'Sweden', 'Malmo');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (49, 'STO', 'Stockholm Arlanda Airport', 'Sweden', 'Stockholm');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (50, 'OSL', 'Oslo Lufthavn', 'Norway', 'Oslo');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (51, 'BGO', 'Bergen Lufthavn', 'Norway', 'Bergen');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (52, 'HEL', 'Helsinki Vantaan lentoasema', 'Finland', 'Helsinki');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (53, 'RIX', 'Starptautiskā lidosta Rīga', 'Latvia', 'Riga');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (54, 'LED', 'Аэропорт Пулково', 'Russia', 'Sankt Petersbourgh');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (55, 'DME', 'Московский аэропорт Домодедово', 'Russia', 'Moskov');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (56, 'VKO', 'Международный аэропорт Внуково', 'Russia', 'Moskov');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (57, 'BRU', 'Brussels Airport', 'Belgium', 'Brussels');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (58, 'DUB', 'Aerfort Bhaile Átha Cliath', 'Ireland', 'Dublin');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (59, 'STN', 'London Stansted Airport', 'United Kingdom', 'London');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (60, 'LHR', 'Heathrow Airport', 'United Kingdom', 'London');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (61, 'LGW', 'Gatwick Airport', 'United Kingdom', 'London');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (62, 'BHX', 'Birmingham Airport', 'United Kingdom', 'London');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (63, 'MAN', 'Manchester Airport', 'United Kingdom', 'London');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (64, 'NCL', 'Newcastle International Airport', 'United Kingdom', 'Newcastle');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (65, 'LPL', 'Liverpool John Lennon Airport', 'United Kingdom', 'Liverpool');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (66, 'EDI', 'Edinburgh Airport', 'United Kingdom', 'Edinburgh');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (67, 'GLA', 'Glasgow Prestwick Airport', 'United Kingdom', 'Glasgow');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (68, 'RKV', 'Keflavíkurflugvöllur', 'Iceland', 'Rejkjavik');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (69, 'YUL', 'Montréal Pierre Elliott Trudeau International Airport', 'Canada', 'Montreal');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (70, 'YQB', 'Québec City Jean Lesage International Airport', 'Canada', 'Quebec');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (71, 'YYZ', 'Lester B. Pearson International Airport', 'Canada', 'Toronto');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (72, 'YOW', 'Macdonald Cartier International Airport', 'Canada', 'Ottawa');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (73, 'YWG', 'Winnipeg James Armstrong Richardson International Airport', 'Canada', 'Winnipeg');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (74, 'YYC', 'Calgary International Airport', 'Canada', 'Calgary');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (75, 'YVR', 'Vancouver International Airport', 'Canada', 'Vancouver');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (76, 'SEA', 'Seattle Tacoma International Airport', 'United States', 'Seattle');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (77, 'PDX', 'Portland International Airport', 'United States', 'Portland');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (78, 'SMF', 'Sacramento International Airport', 'United States', 'Sacramento');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (79, 'SFO', 'San Francisco International Airport', 'United States', 'San Francisco');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (80, 'LAX', 'Los Angeles International Airport', 'United States', 'Los Angeles');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (81, 'SAN', 'San Diego International Airport', 'United States', 'San Diego');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (82, 'LAS', 'Las Vegas International Airport', 'United States', 'Las Vegas');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (83, 'PHX', 'Phoenix Sky Harbor International Airport', 'United States', 'Phoenix');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (84, 'TUS', 'Tuscon International Airport', 'United States', 'Tuscon');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (85, 'AUS', 'Austin International Airport', 'United States', 'Austin');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (86, 'IAH', 'George Bush Intercontinental Airport', 'United States', 'Houston');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (87, 'SAT', 'San Antonio International Airport', 'United States', 'San Antonio');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (88, 'DFW', 'Dallas/Fort Worth International Airport', 'United States', 'Dallas');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (89, 'MIA', 'Miami International Airport', 'United States', 'Miami');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (90, 'ORL', 'Orlando International Airport', 'United States', 'Orlando');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (91, 'ATL', 'Hartsfield Jackson Atlanta International Airport', 'United States', 'Atlanta');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (92, 'BNA', 'Nashville International Airport', 'United States', 'Nashville');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (93, 'MCI', 'Kansas City International Airport', 'United States', 'Kansas City');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (94, 'CHI', 'OHare International Airport', 'United States', 'Chicago');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (95, 'DTW', 'Detroit Metropolitan Wayne County Airport', 'United States', 'Detroit');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (96, 'JFK', 'John F. Kennedy International Airport', 'United States', 'New York');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (97, 'BOS', 'General Edward Lawrence Logan International Airport', 'United States', 'Boston');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (98, 'DCA', 'Washington Dulles International Airport', 'United States', 'Washington');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (99, 'PHL', 'Philadelphia International Airport', 'United States', 'Philadelphia');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (100, 'MSP', 'Minneapolis Saint Paul International Airport', 'United States', 'Minneapolis');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city) VALUES (101, 'MEX', 'Aeropuerto Internacional Benito Juárez', 'Mexico', 'Mexico City');
