CREATE TABLE airline (
    airline_id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    name varchar NOT NULL UNIQUE,
    airline_code char(3) NOT NULL UNIQUE
);


CREATE TABLE airport (
    airport_id smallint GENERATED BY DEFAULT AS IDENTITY NULL UNIQUE,
    airport_code char(3) NOT NULL UNIQUE,
    full_name varchar NOT NULL,
    origin_country varchar,
    origin_city varchar,
    geographic_location varchar NOT NULL
);


CREATE TABLE route (
    route_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    departure_airport_id smallint NOT NULL,
    arrival_airport_id smallint NOT NULL,
    departure_datetime date,
    arrival_datetime date,

    CONSTRAINT departure_airport_fk
        FOREIGN KEY (departure_airport_id) REFERENCES airport(airport_id),

    CONSTRAINT arrival_airport_fk
        FOREIGN KEY (arrival_airport_id) REFERENCES airport(airport_id)
) SPLIT INTO 16 TABLETS;


CREATE TABLE flight (
    flight_id int NULL,
    airline_id smallint NOT NULL,
    route_id int NOT NULL,
    flight_code char(12) NOT NULL,
    duration time,
    passengers smallint,
    flight_type varchar NOT NULL,

    CONSTRAINT airline_fk
        FOREIGN KEY (airline_id) REFERENCES airline(airline_id),

    CONSTRAINT route_fk
        FOREIGN KEY (route_id) REFERENCES route(route_id)
) PARTITION BY LIST(flight_type);


CREATE TABLE flight_europe
    PARTITION OF flight(
        flight_id,
        airline_id,
        route_id,
        flight_code,
        duration,
        passengers,
        flight_type
) FOR VALUES IN ('Internal Europe');


CREATE TABLE flight_america
    PARTITION OF flight(
        flight_id,
        airline_id,
        route_id,
        flight_code,
        duration,
        passengers,
        flight_type
) FOR VALUES IN ('Internal North America');


CREATE TABLE flight_default
    PARTITION OF flight(
        flight_id,
        airline_id,
        route_id,
        flight_code,
        duration,
        passengers,
        flight_type
) DEFAULT;
