version: '2'

volumes:
  yb-master-data-1:
  yb-tserver-data-1:
  yb-tserver-data-2:

services:
  yb-master:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-n1
      volumes:
      - yb-master-data-1:/mnt/master
      - .:/home/flight_db
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=1",
                "--yb_num_shards_per_tserver=1",
                "--ysql_num_shards_per_tserver=1",
                "--placement_cloud=local",
                "--placement_region=europe",
                "--placement_zone=europe-2a"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master

  yb-tserver-1:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-n1-europe
      volumes:
      - yb-tserver-data-1:/mnt/tserver-1
      - .:/home/flight_db
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver-1",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1-europe:9100",
                "--tserver_master_addrs=yb-master-n1:7100",
                "--yb_num_shards_per_tserver=1",
                "--ysql_num_shards_per_tserver=1",
                "--placement_cloud=local",
                "--placement_region=europe",
                "--placement_zone=europe-1a"]
      ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-master

  yb-tserver-2:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-n2-america
      volumes:
      - yb-tserver-data-2:/mnt/tserver-2
      - .:/home/flight_db
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver-2",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n2-america:9101",
                "--tserver_master_addrs=yb-master-n1:7100",
                "--yb_num_shards_per_tserver=1",
                "--ysql_num_shards_per_tserver=1",
                "--placement_cloud=local",
                "--placement_region=america",
                "--placement_zone=america-1a",
                "--webserver_port=9001",
                "--pgsql_proxy_bind_address=0.0.0.0:5434",
                "--cql_proxy_bind_address=0.0.0.0:9043",
                "--redis_proxy_bind_address=0.0.0.0:6380"]
      ports:
      - "9043:9043"
      - "5434:5434"
      - "9001:9001"
      environment:
        SERVICE_5434_NAME: ysql
        SERVICE_9043_NAME: ycql
        SERVICE_6380_NAME: yedis
        SERVICE_9001_NAME: yb-tserver
      depends_on:
      - yb-master