INSERT INTO airline (name, airline_code) VALUES ('Ryanair', 'RYR');
INSERT INTO airline (name, airline_code) VALUES ('Lufthansa Group', 'DLH');
INSERT INTO airline (name, airline_code) VALUES ('International Airlines Group', 'AAN');
INSERT INTO airline (name, airline_code) VALUES ('Air France-KLM', 'SEU');
INSERT INTO airline (name, airline_code) VALUES ('Easyjet', 'EZY');
INSERT INTO airline (name, airline_code) VALUES ('Wizz Air', 'WZZ');
INSERT INTO airline (name, airline_code) VALUES ('American Airlines', 'AAL');
INSERT INTO airline (name, airline_code) VALUES ('Delta Air Lines', 'DAL');
INSERT INTO airline (name, airline_code) VALUES ('Southwest Airlines', 'SWA');
INSERT INTO airline (name, airline_code) VALUES ( 'Air Canada', 'ROU');
INSERT INTO airline (name, airline_code) VALUES ( 'LOT Polish Airlines', 'LOT');
