INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (1, 'PDL', 'Ponta Delgada Joao Paulo II', 'Portugal', 'Ponta Delgada', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (2, 'FAO', 'Faro Airport', 'Portugal', 'Faro', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (3, 'LIS', 'Portela', 'Portugal', 'Lisbon', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (4, 'OPO', 'Franciso De Sa Carneiro', 'Portugal', 'Porto', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (5, 'SJZ', 'Sao Jorge Airport', 'Portugal', 'Madeira', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (6, 'MAD', 'Madrid-Barajas Adolfo Suárez Airport', 'Spain', 'Madrid', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (7, 'AGP', 'Málaga-Costa del Sol Airport', 'Spain', 'Malaga', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (8, 'BCN', 'Josep Tarradellas Barcelona-El Prat Airport', 'Spain', 'Barcelona', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (9, 'PMI', 'Palma de Mallorca Airport', 'Spain', 'Mallorca', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (10, 'LPA', 'Gran Canaria Airport', 'Spain', 'Gran Canaria', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (11, 'BOD', 'Bordeaux Airport', 'France', 'Bordeaux', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (12, 'MRS', 'Marseille Provence Airport', 'France', 'Marseille', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (13, 'LYS', 'Lyon Saint Exupéry Airport', 'France', 'Lyon', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (14, 'CDG', 'Paris Charles de Gaulle Airport', 'France', 'Paris', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (15, 'PMO', 'Falcone Borsellino Airport', 'Italy', 'Palermo', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (16, 'CTA', 'Aeroporto di Catania Fontanarossa', 'Italy', 'Catania', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (17, 'BRI', 'Aeroporto Internazionale di Bari: Karol Wojtyla', 'Italy', 'Bari', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (18, 'CIA', 'Aeroporto Internazionale di Roma Ciampino G. B. Pastine', 'Italy', 'Rome', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (19, 'PSA', 'Aeroporto Internazionale Galileo Galilei Pisa', 'Italy', 'Pisa', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (20, 'TRN', 'Torino Airport', 'Italy', 'Torino', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (21, 'MIL', 'Aeroporto di Milano Linate', 'Italy', 'Milan', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (22, 'CAG', 'Cagliari Elmas Airport', 'Italy', 'Calgiari', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (23, 'MLA', 'Malta International Airport', 'Malta', 'Luqa', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (24, 'ZRH', 'Flughafen Zürich', 'Switzerland', 'Zurich', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (25, 'OTZ', 'Flughafen Wien', 'Austria', 'Wien', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (26, 'LJU', 'Letališče Jožeta Pučnika Ljubljana', 'Slovenia', 'Ljubljana', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (27, 'RJK', 'Zračna luka Rijeka', 'Croatia', 'Riejka', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (28, 'CFU', 'Αεροδρόμιο της Κέρκυρας', 'Greece', 'Corfu', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (29, 'ATH', 'Διεθνής Αερολιμένας Αθηνών', 'Greece', 'Athens', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (30, 'SKG', 'Κρατικός Αερολιμένας Νέας Αγχιάλου', 'Greece', 'Thessaloniki', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (31, 'JMK', 'Αεροδρόμιο Μυκόνου', 'Greece', 'Mykonos', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (32, 'CHQ', 'Αεροδρόμιο Χανίων Ιωάννης Δασκαλογιάννης', 'Greece', 'Chania', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (33, 'AYT', 'Antalya Havalimanı', 'Turkey', 'Antalya', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (34, 'SAW', 'Sabiha Gökçen Uluslararası Havalimanı', 'Turkey', 'Istambul', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (35, 'SKP', 'Меѓународен аеродром Скопје', 'North Macedonia', 'Skopje', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (36, 'WRO', 'Wrocław Nicolaus Copernicus Airport', 'Poland', 'Wroclaw', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (37, 'KRK', 'Kraków Airport im. Jana Pawła II', 'Poland', 'Krakow', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (38, 'WAW', 'Lotnisko Chopina', 'Poland', 'Warsaw', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (39, 'GDN', 'Port Lotniczy Gdańsk im. Lecha Wałęsy', 'Poland', 'Gdansk', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (40, 'MUC', 'Flughafen München', 'Germany', 'Munich', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (41, 'DUS', 'Flughafen Düsseldorf', 'Germany', 'Dusseldorf', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (42, 'TXL', 'Flughafen Berlin Tegel', 'Germany', 'Berlin', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (43, 'FRA', 'Frankfurt Flughafen', 'Germany', 'Frankfurt', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (44, 'NUE', 'Airport Nürnberg', 'Germany', 'Nurnberg', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (45, 'AMS', 'Amsterdam Airport Schiphol', 'Netherlands', 'Amsterdam', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (46, 'KOB', 'Københavns Lufthavn', 'Denmark', 'Copenhagen', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (47, 'AAL', 'Aalborg Lufthavn', 'Denmark', 'Aalborg', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (48, 'MMX', 'Malmö Airport', 'Sweden', 'Malmo', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (49, 'STO', 'Stockholm Arlanda Airport', 'Sweden', 'Stockholm', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (50, 'OSL', 'Oslo Lufthavn', 'Norway', 'Oslo', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (51, 'BGO', 'Bergen Lufthavn', 'Norway', 'Bergen', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (52, 'HEL', 'Helsinki Vantaan lentoasema', 'Finland', 'Helsinki', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (53, 'RIX', 'Starptautiskā lidosta Rīga', 'Latvia', 'Riga', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (54, 'LED', 'Аэропорт Пулково', 'Russia', 'Sankt Petersbourgh', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (55, 'DME', 'Московский аэропорт Домодедово', 'Russia', 'Moskov', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (56, 'VKO', 'Международный аэропорт Внуково', 'Russia', 'Moskov', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (57, 'BRU', 'Brussels Airport', 'Belgium', 'Brussels', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (58, 'DUB', 'Aerfort Bhaile Átha Cliath', 'Ireland', 'Dublin', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (59, 'STN', 'London Stansted Airport', 'United Kingdom', 'London', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (60, 'LHR', 'Heathrow Airport', 'United Kingdom', 'London', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (61, 'LGW', 'Gatwick Airport', 'United Kingdom', 'London', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (62, 'BHX', 'Birmingham Airport', 'United Kingdom', 'London', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (63, 'MAN', 'Manchester Airport', 'United Kingdom', 'London', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (64, 'NCL', 'Newcastle International Airport', 'United Kingdom', 'Newcastle', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (65, 'LPL', 'Liverpool John Lennon Airport', 'United Kingdom', 'Liverpool', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (66, 'EDI', 'Edinburgh Airport', 'United Kingdom', 'Edinburgh', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (67, 'GLA', 'Glasgow Prestwick Airport', 'United Kingdom', 'Glasgow', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (68, 'RKV', 'Keflavíkurflugvöllur', 'Iceland', 'Rejkjavik', 'Europe');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (69, 'YUL', 'Montréal Pierre Elliott Trudeau International Airport', 'Canada', 'Montreal', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (70, 'YQB', 'Québec City Jean Lesage International Airport', 'Canada', 'Quebec', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (71, 'YYZ', 'Lester B. Pearson International Airport', 'Canada', 'Toronto', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (72, 'YOW', 'Macdonald Cartier International Airport', 'Canada', 'Ottawa', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (73, 'YWG', 'Winnipeg James Armstrong Richardson International Airport', 'Canada', 'Winnipeg', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (74, 'YYC', 'Calgary International Airport', 'Canada', 'Calgary', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (75, 'YVR', 'Vancouver International Airport', 'Canada', 'Vancouver', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (76, 'SEA', 'Seattle Tacoma International Airport', 'United States', 'Seattle', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (77, 'PDX', 'Portland International Airport', 'United States', 'Portland', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (78, 'SMF', 'Sacramento International Airport', 'United States', 'Sacramento', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (79, 'SFO', 'San Francisco International Airport', 'United States', 'San Francisco', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (80, 'LAX', 'Los Angeles International Airport', 'United States', 'Los Angeles', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (81, 'SAN', 'San Diego International Airport', 'United States', 'San Diego', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (82, 'LAS', 'Las Vegas International Airport', 'United States', 'Las Vegas', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (83, 'PHX', 'Phoenix Sky Harbor International Airport', 'United States', 'Phoenix', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (84, 'TUS', 'Tuscon International Airport', 'United States', 'Tuscon', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (85, 'AUS', 'Austin International Airport', 'United States', 'Austin', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (86, 'IAH', 'George Bush Intercontinental Airport', 'United States', 'Houston', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (87, 'SAT', 'San Antonio International Airport', 'United States', 'San Antonio', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (88, 'DFW', 'Dallas/Fort Worth International Airport', 'United States', 'Dallas', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (89, 'MIA', 'Miami International Airport', 'United States', 'Miami', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (90, 'ORL', 'Orlando International Airport', 'United States', 'Orlando', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (91, 'ATL', 'Hartsfield Jackson Atlanta International Airport', 'United States', 'Atlanta', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (92, 'BNA', 'Nashville International Airport', 'United States', 'Nashville', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (93, 'MCI', 'Kansas City International Airport', 'United States', 'Kansas City', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (94, 'CHI', 'OHare International Airport', 'United States', 'Chicago', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (95, 'DTW', 'Detroit Metropolitan Wayne County Airport', 'United States', 'Detroit', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (96, 'JFK', 'John F. Kennedy International Airport', 'United States', 'New York', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (97, 'BOS', 'General Edward Lawrence Logan International Airport', 'United States', 'Boston', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (98, 'DCA', 'Washington Dulles International Airport', 'United States', 'Washington', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (99, 'PHL', 'Philadelphia International Airport', 'United States', 'Philadelphia', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (100, 'MSP', 'Minneapolis Saint Paul International Airport', 'United States', 'Minneapolis', 'North America');
INSERT INTO airport (airport_id, airport_code, full_name, origin_country, origin_city, geographic_location) VALUES (101, 'MEX', 'Aeropuerto Internacional Benito Juárez', 'Mexico', 'Mexico City', 'North America');

